4. Функції
Beetroot-Academy/kholiavskiy__lessons pull request #20
Opened 2022-06-01 14:47 UTC by vohol

2022-06-11 17:30 UTC, AlexKojuhar requested changes

2022-06-11 17:30 UTC, AlexKojuhar commented on hw-20/js/script.js
> +  let summOfDividers = 0;
`summOfDividers`  --> `dividersSum`

2022-06-11 17:30 UTC, AlexKojuhar commented on hw-20/js/script.js
> +console.log(isPerfectNum(6));
`isPerfectNum` --> `isNumPerfect`
Прикметник має бути вкінці

2022-06-11 17:30 UTC, AlexKojuhar commented on hw-20/js/script.js
> +function showPerfectNumsInFange(min, max) {
`showPerfectNumsInFange` --> `showPerfectNumsInRange`

2022-06-13 13:45 UTC, vohol commented on hw-20/js/script.js
> +  let summOfDividers = 0;
Исправил

2022-06-13 13:45 UTC, vohol commented on hw-20/js/script.js
> +console.log(isPerfectNum(6));
понял

2022-06-13 13:46 UTC, vohol commented on hw-20/js/script.js
> +function showPerfectNumsInFange(min, max) {
ой)) не заметил) исправил

2022-06-19 18:17 UTC, merged