5. Масиви
Beetroot-Academy/kholiavskiy__lessons pull request #21
Opened 2022-06-05 17:15 UTC by vohol

2022-06-11 17:32 UTC, AlexKojuhar commented on hw-22/js/script.js
> +	return array.filter((product) => product.bought == true);
`return array.filter((product) => product.bought);`

2022-06-11 17:35 UTC, AlexKojuhar requested changes

2022-06-11 17:35 UTC, AlexKojuhar commented on hw-22/js/script.js
> +	return array.filter((product) => product.bought == false);
`return array.filter((product) => !!product.bought);`

2022-06-13 13:49 UTC, vohol commented on hw-22/js/script.js
> +	return array.filter((product) => product.bought == false);
понял, исправил

2022-06-13 13:49 UTC, vohol commented on hw-22/js/script.js
> +	return array.filter((product) => product.bought == true);
понял, исправил

2022-06-19 18:04 UTC, AlexKojuhar approved these changes

2022-06-19 18:04 UTC, merged