8. Верстка секції Our Service макету Creative Agency
Beetroot-Academy/kholiavskiy__lessons pull request #7
Opened 2022-04-22 09:22 UTC by vohol

2022-04-23 18:38 UTC, AlexKojuhar requested changes

2022-04-23 18:38 UTC, AlexKojuhar commented on hw-8/fonts/demo.html
> +<html lang="en">
Зайвий файл

2022-04-23 18:38 UTC, AlexKojuhar commented on hw-8/fonts/stylesheet.css
> +@font-face {
Зайвий файл

2022-04-24 19:32 UTC, vohol commented on hw-8/fonts/demo.html
> +<html lang="en">
видалив

2022-04-24 19:32 UTC, vohol commented on hw-8/fonts/stylesheet.css
> +@font-face {
видалив

2022-05-04 18:46 UTC, merged